"""Test script for the two-agent sequential workflow (Architect Bee + Developer Bee)."""

import httpx
import json
from datetime import datetime

# Configuration
API_URL = "http://localhost:8000/api/generate"
JWT_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZmVkNzViZC0zNTMxLTRmZGUtYjY1Ny04ZmVjYTZkZDUwYjEiLCJlbWFpbCI6InRlc3RAaGl2ZWNvZHIuY29tIiwiYXVkIjoiYXV0aGVudGljYXRlZCIsInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiaWF0IjoxNzY4NjIzMjk2LCJleHAiOjE3Njg3MDk2OTZ9.GD9jsbT9KCeHr4Yg0e_11DSIl5XZYLFQu0zOqI5D-n8"

# Test prompt - a more complex example to test the two-agent workflow
REQUIREMENTS = """
Create a recipe sharing API with users, recipes, ingredients, and meal plans
"""


def test_two_agent_workflow():
    """Test the two-agent sequential workflow."""

    print(f"\n{'='*80}")
    print("Testing Two-Agent Workflow: Architect Bee + Developer Bee")
    print(f"{'='*80}\n")

    print(f"Endpoint: {API_URL}")
    print(f"\nRequirements:")
    print(f"{REQUIREMENTS}")
    print(f"\nSending request...\n")
    print("This will take a few minutes as two agents work sequentially:")
    print("  1. Architect Bee - Designs the architecture")
    print("  2. Developer Bee - Generates the code")
    print()

    headers = {
        "Authorization": f"Bearer {JWT_TOKEN}",
        "Content-Type": "application/json"
    }

    payload = {
        "requirements": REQUIREMENTS
    }

    try:
        # Send POST request with extended timeout for two-agent workflow
        with httpx.Client(timeout=600.0) as client:  # 10 minute timeout
            response = client.post(API_URL, headers=headers, json=payload)

        print(f"Status Code: {response.status_code}")
        print(f"{'='*80}\n")

        if response.status_code == 200:
            result = response.json()

            print("SUCCESS!\n")
            print(f"Generation ID: {result.get('id')}")
            print(f"Created At: {result.get('created_at')}")

            # Extract and display the agent logs
            agent_log = result.get('agent_log', '')

            print(f"\n{'='*80}")
            print("AGENT WORKFLOW LOG:")
            print(f"{'='*80}")

            # Show Phase 1 (Architect Bee)
            if "PHASE 1: ARCHITECTURE DESIGN" in agent_log:
                phase1_start = agent_log.find("PHASE 1: ARCHITECTURE DESIGN")
                phase2_start = agent_log.find("PHASE 2: CODE GENERATION")

                if phase2_start > phase1_start:
                    print("\n--- PHASE 1: ARCHITECT BEE ---")
                    phase1_log = agent_log[phase1_start:phase2_start].strip()
                    # Truncate if too long
                    if len(phase1_log) > 2000:
                        print(f"{phase1_log[:2000]}...")
                        print(f"\n[Truncated - {len(phase1_log)} total characters]")
                    else:
                        print(phase1_log)

                    print("\n--- PHASE 2: DEVELOPER BEE ---")
                    phase2_log = agent_log[phase2_start:].strip()
                    # Truncate if too long
                    if len(phase2_log) > 2000:
                        print(f"{phase2_log[:2000]}...")
                        print(f"\n[Truncated - {len(phase2_log)} total characters]")
                    else:
                        print(phase2_log)
            else:
                print(agent_log[:3000] if len(agent_log) > 3000 else agent_log)

            print(f"\n{'='*80}")
            print("GENERATED CODE FILES:")
            print(f"{'='*80}\n")

            # Display generated code
            code = result.get('code', {})
            for filename, content in code.items():
                print(f"\n--- {filename} ---")
                # Show first 100 lines of each file
                lines = content.split('\n')
                if len(lines) > 100:
                    print('\n'.join(lines[:100]))
                    print(f"\n... [{len(lines) - 100} more lines]")
                else:
                    print(content)
                print(f"--- End of {filename} ---\n")

            # Save to file for easier viewing
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_file = f"two_agent_output_{timestamp}.json"
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(result, f, indent=2, ensure_ascii=False)

            print(f"\n{'='*80}")
            print(f"Full output saved to: {output_file}")
            print(f"{'='*80}\n")

            # Summary
            print(f"\nSUMMARY:")
            print(f"- Two-agent workflow completed successfully")
            print(f"- Architecture designed by Architect Bee")
            print(f"- Code generated by Developer Bee")
            print(f"- Generated files: {', '.join(code.keys())}")

        else:
            print("ERROR!\n")
            print(f"Response: {response.text}")

    except httpx.TimeoutException:
        print("\nRequest timed out!")
        print("The two-agent workflow is taking longer than expected.")
        print("This might be normal for complex requirements.")

    except httpx.ConnectError:
        print("\nConnection Error!")
        print("Make sure the server is running on http://localhost:8000")

    except Exception as e:
        print(f"\nUnexpected Error!")
        print(f"Error: {str(e)}")


if __name__ == "__main__":
    test_two_agent_workflow()
